-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.app_orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_number text DEFAULT ('ORD-'::text || (nextval('order_number_seq'::regclass))::text),
  order_date date NOT NULL,
  client_name text NOT NULL,
  godown_name text NOT NULL,
  item_name text NOT NULL,
  rate numeric DEFAULT 0,
  qty integer DEFAULT 0,
  current_stock text,
  intransit_qty integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  submittedby text,
  CONSTRAINT app_orders_pkey PRIMARY KEY (id)
);
CREATE TABLE public.daily_stock_summary (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  date date NOT NULL DEFAULT CURRENT_DATE,
  godown_id text NOT NULL,
  product_id text NOT NULL,
  opening_stock numeric DEFAULT 0,
  in_stock numeric DEFAULT 0,
  out_stock numeric DEFAULT 0,
  closing_stock numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT daily_stock_summary_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dispatch_completed_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  dispatch_id uuid,
  dispatch_number text,
  dispatch_date date,
  complete_date date,
  client_name text,
  product_name text,
  godown_name text,
  order_qty integer,
  dispatch_qty integer,
  crm_name text,
  status text DEFAULT 'Completed'::text,
  created_at timestamp with time zone DEFAULT now(),
  order_no text,
  is_skip text,
  CONSTRAINT dispatch_completed_log_pkey PRIMARY KEY (id),
  CONSTRAINT dispatch_completed_log_dispatch_id_fkey FOREIGN KEY (dispatch_id) REFERENCES public.dispatch_plans(id)
);
CREATE TABLE public.dispatch_plans (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid,
  planned_qty integer NOT NULL DEFAULT 0,
  planned_date date NOT NULL,
  gst_included text DEFAULT 'Yes'::text,
  godown_name text,
  submitted_by text,
  created_at timestamp with time zone DEFAULT now(),
  informed_at timestamp with time zone,
  informed_before_dispatch boolean DEFAULT false,
  informed_after_dispatch boolean DEFAULT false,
  dispatch_completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  dispatch_number text,
  status text DEFAULT 'Planned'::text,
  informed_after timestamp with time zone,
  is_skip boolean,
  product_name text,
  order_qty integer,
  client_name text,
  order_number text,
  CONSTRAINT dispatch_plans_pkey PRIMARY KEY (id),
  CONSTRAINT dispatch_plans_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.app_orders(id)
);
CREATE TABLE public.godowns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  godown_id text NOT NULL UNIQUE,
  name text NOT NULL,
  address text,
  contact_person text,
  contact_number text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT godowns_pkey PRIMARY KEY (id)
);
CREATE TABLE public.master_customers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_name text NOT NULL,
  location text,
  customer_number text,
  gst_number text,
  crm_follow_up text,
  email_id text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT master_customers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.master_product (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT master_product_pkey PRIMARY KEY (id)
);
CREATE TABLE public.master_vendors (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  vendor_name text NOT NULL,
  location text,
  email_id text,
  gst_number text,
  vendor_number text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT master_vendors_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pc_reports (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  unique_number text,
  planned_date date,
  step_name text,
  who text,
  client_name text,
  godown text,
  item_name text,
  rate numeric DEFAULT 0,
  order_qty integer DEFAULT 0,
  status text DEFAULT 'Running'::text,
  remarks text,
  planning_qty integer DEFAULT 0,
  remaining_planning_qty integer DEFAULT 0,
  qty_delivered integer DEFAULT 0,
  order_cancel boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  remark text,
  report text,
  CONSTRAINT pc_reports_pkey PRIMARY KEY (id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  unit text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  opening_quantity numeric DEFAULT 0,
  closing_quantity numeric DEFAULT 0,
  mux text,
  godown_id text,
  quantity numeric DEFAULT 0,
  godown_name text,
  master_product_id uuid,
  product_type text,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_godown_id_fkey FOREIGN KEY (godown_id) REFERENCES public.godowns(godown_id),
  CONSTRAINT products_master_product_id_fkey FOREIGN KEY (master_product_id) REFERENCES public.master_product(id)
);
CREATE TABLE public.purchase_delivery (
  id bigint NOT NULL DEFAULT nextval('purchase_delivery_id_seq'::regclass),
  indent_id bigint,
  indent_number character varying,
  delivery_number character varying,
  product_name character varying,
  vendor_name character varying,
  godown_name text,
  planned_qty_kg numeric,
  planned_qty_bags integer,
  received_qty_kg numeric,
  received_qty_bags integer,
  rate numeric,
  delivery_date date,
  lr_number character varying,
  vehicle_number character varying,
  remarks text,
  delivery_status character varying DEFAULT 'Pending'::character varying,
  arrival_status character varying DEFAULT 'Not Arrived'::character varying,
  created_by character varying,
  created_at timestamp with time zone DEFAULT now(),
  transporter_name text,
  driver_phone text,
  CONSTRAINT purchase_delivery_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_delivery_indent_id_fkey FOREIGN KEY (indent_id) REFERENCES public.purchase_indent(id)
);
CREATE TABLE public.purchase_indent (
  id bigint NOT NULL DEFAULT nextval('purchase_indent_id_seq'::regclass),
  indent_number character varying NOT NULL,
  product_name character varying NOT NULL,
  vendor_name character varying,
  qty_kg numeric,
  qty_bags integer,
  rate numeric,
  vendor_approval boolean DEFAULT false,
  created_by character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  godown_name text,
  indent_type character varying DEFAULT 'Direct'::character varying,
  indent_date date,
  remarks text,
  CONSTRAINT purchase_indent_pkey PRIMARY KEY (id)
);
CREATE TABLE public.purchase_indent_cancellations (
  id bigint NOT NULL DEFAULT nextval('purchase_indent_cancellations_id_seq'::regclass),
  indent_number character varying NOT NULL,
  product_name character varying NOT NULL,
  vendor_name character varying,
  original_qty_kg numeric,
  original_qty_bags integer,
  cancelled_qty_kg numeric DEFAULT 0,
  cancelled_qty_bags integer DEFAULT 0,
  rate numeric,
  vendor_approval boolean,
  reason text,
  created_by character varying,
  created_at timestamp with time zone,
  cancelled_by character varying,
  cancelled_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT purchase_indent_cancellations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.stock_management (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entry_id text NOT NULL UNIQUE,
  godown_id text NOT NULL,
  product_id text NOT NULL,
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['in'::text, 'out'::text, 'adjustment'::text])),
  quantity numeric NOT NULL,
  opening_stock numeric,
  closing_stock numeric,
  reference_number text,
  date date NOT NULL DEFAULT CURRENT_DATE,
  notes text,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  transporter_id uuid,
  lr_number character varying,
  from_location text,
  freight_amount numeric,
  CONSTRAINT stock_management_pkey PRIMARY KEY (id),
  CONSTRAINT stock_management_from_location_fkey FOREIGN KEY (from_location) REFERENCES public.godowns(godown_id),
  CONSTRAINT stock_management_transporter_id_fkey FOREIGN KEY (transporter_id) REFERENCES public.transporters(transporter_id)
);
CREATE TABLE public.stock_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  notification_type text NOT NULL CHECK (notification_type = ANY (ARRAY['stock_in'::text, 'stock_out'::text, 'low_stock'::text])),
  title text NOT NULL,
  message text NOT NULL,
  product_id text,
  godown_id text,
  related_id text,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stock_notifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transporters (
  transporter_id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  vehicle_number character varying,
  driver_phone character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transporters_pkey PRIMARY KEY (transporter_id)
);
CREATE TABLE public.users (
  user_id uuid NOT NULL DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  designation text,
  date_of_birth date,
  gender text,
  email text,
  phone_number text,
  current_address text,
  username text NOT NULL UNIQUE,
  password text NOT NULL,
  role text,
  is_active boolean DEFAULT true,
  profile_picture text,
  created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'Asia/Kolkata'::text),
  page_access json,
  CONSTRAINT users_pkey PRIMARY KEY (user_id)
);
CREATE TABLE public.whatsapp_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  recipient_name text,
  phone_number text,
  message_type text,
  message_content text,
  status text,
  error_message text,
  sender_name text,
  reference_id text,
  stage text,
  is_read boolean DEFAULT true,
  message_id text,
  CONSTRAINT whatsapp_logs_pkey PRIMARY KEY (id)
);